context: {}
entries:
- attrs:
    authentication: require_authenticated
    background: ''
    compatibility_mode: false
    denied_action: message_continue
    designation: stage_configuration
    layout: stacked
    name: Profile
    policy_engine_mode: any
    title: Profile
  conditions: []
  identifiers:
    pk: fd505a14-d9e0-4d7d-a6ad-3493df374242
    slug: ietf-user-settings
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    field_key: attributes.location
    initial_value: return request.user.attributes.get("location", "")
    initial_value_expression: true
    label: Location
    name: ietf-user-settings-field-location
    order: 500
    placeholder: "e.g. Montr\xE9al, Canada"
    placeholder_expression: false
    required: false
    sub_text: ''
    type: text
  conditions: []
  identifiers:
    pk: 5c46e8bf-74f3-4266-9f53-0fae5e384f86
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: name
    initial_value: "try:\n    return user.name\nexcept:\n    return ''"
    initial_value_expression: true
    label: Full Name
    name: ietf-user-settings-field-name
    order: 201
    placeholder: e.g. John Doe
    placeholder_expression: false
    required: true
    sub_text: ''
    type: text
  conditions: []
  identifiers:
    pk: 6d1bba97-eb84-42cf-a50a-fbfc68fccddc
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: attributes.company
    initial_value: return request.user.attributes.get("company", "")
    initial_value_expression: true
    label: Company / Affiliation
    name: ietf-user-settings-field-company
    order: 600
    placeholder: e.g. ACME Corporation
    placeholder_expression: false
    required: false
    sub_text: ''
    type: text
  conditions: []
  identifiers:
    pk: fa8953a3-2ced-4734-bfca-6a954fe97aa2
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: email
    initial_value: "try:\n    return user.email\nexcept:\n    return ''"
    initial_value_expression: true
    label: Email Address
    name: ietf-user-settings-field-email
    order: 250
    placeholder: e.g. user@example.com
    placeholder_expression: false
    required: true
    sub_text: Note that changing this field will trigger an email validation to confirm
      you own this email address.
    type: text
  conditions: []
  identifiers:
    pk: e4771802-933d-4c46-9512-31042cfbcd5c
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    field_key: attributes.pronouns
    initial_value: return request.user.attributes.get("pronouns", "")
    initial_value_expression: true
    label: Pronouns
    name: ietf-user-settings-field-pronouns
    order: 400
    placeholder: e.g. he/him, she/her
    placeholder_expression: false
    required: false
    sub_text: Optionally provide your personal pronouns. These will be displayed on
      your public Datatracker profile page, alongside your name in Meetecho, etc.
    type: text
  conditions: []
  identifiers:
    pk: 25e3e4a4-aa8d-4d31-bf41-5efd73620f77
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    execution_logging: false
    expression: "from authentik.core.models import (\n    USER_ATTRIBUTE_CHANGE_EMAIL,\n\
      \    USER_ATTRIBUTE_CHANGE_NAME,\n    USER_ATTRIBUTE_CHANGE_USERNAME\n)\nprompt_data\
      \ = request.context.get(\"prompt_data\")\n\nif not request.user.group_attributes(request.http_request).get(\n\
      \    USER_ATTRIBUTE_CHANGE_EMAIL, request.http_request.tenant.default_user_change_email\n\
      ):\n    if prompt_data.get(\"email\") != request.user.email:\n        ak_message(\"\
      Not allowed to change email address.\")\n        return False\n\nif not request.user.group_attributes(request.http_request).get(\n\
      \    USER_ATTRIBUTE_CHANGE_NAME, request.http_request.tenant.default_user_change_name\n\
      ):\n    if prompt_data.get(\"name\") != request.user.name:\n        ak_message(\"\
      Not allowed to change name.\")\n        return False\n\nif not request.user.group_attributes(request.http_request).get(\n\
      \    USER_ATTRIBUTE_CHANGE_USERNAME, request.http_request.tenant.default_user_change_username\n\
      ):\n    if prompt_data.get(\"username\", request.user.username) != request.user.username:\n\
      \        ak_message(\"Not allowed to change username.\")\n        return False\n\
      \nreturn True"
    name: ietf-user-settings-validation
  conditions: []
  identifiers:
    pk: f11a90ac-7fb6-4990-8985-d9b19e8e1700
  model: authentik_policies_expression.expressionpolicy
  permissions: []
  state: present
- attrs:
    create_users_as_inactive: false
    create_users_group: null
    user_creation_mode: never_create
    user_path_template: ''
    user_type: internal
  conditions: []
  identifiers:
    name: ietf-user-settings-write
    pk: 2c69fffd-aded-4d9d-a59c-3d1be0eadf53
  model: authentik_stages_user_write.userwritestage
  permissions: []
  state: present
- attrs:
    fields:
    - 5c46e8bf-74f3-4266-9f53-0fae5e384f86
    - 6d1bba97-eb84-42cf-a50a-fbfc68fccddc
    - fa8953a3-2ced-4734-bfca-6a954fe97aa2
    - e4771802-933d-4c46-9512-31042cfbcd5c
    - 25e3e4a4-aa8d-4d31-bf41-5efd73620f77
    validation_policies:
    - f11a90ac-7fb6-4990-8985-d9b19e8e1700
  conditions: []
  identifiers:
    name: ietf-user-settings
    pk: c089b12a-13f2-4a16-aec9-f21ca4a7885c
  model: authentik_stages_prompt.promptstage
  permissions: []
  state: present
- attrs:
    evaluate_on_plan: false
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 0
    pk: 86d0198a-7333-4d06-a6f6-7b058e127074
    stage: c089b12a-13f2-4a16-aec9-f21ca4a7885c
    target: fd505a14-d9e0-4d7d-a6ad-3493df374242
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    evaluate_on_plan: false
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 1
    pk: 72d0d96e-ea0c-43d6-b6b5-38c90af29bdb
    stage: 2c69fffd-aded-4d9d-a59c-3d1be0eadf53
    target: fd505a14-d9e0-4d7d-a6ad-3493df374242
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-07-21 05:59:00.469434+00:00
version: 1
